inputDir = '/home/dsolop/Music/Lifehouse/2000 - No Name Face'
outputDir = '/home/dsolop/Music/falloutOutput'
songsPerFile = 3

outputNames = [
    'mus_radio_diamond_bettyhutton_hesademon',
    'mus_radio_diamond_bettyhutton_itsaman',
    'mus_radio_diamond_bigmaybelle_wholelottashakingoinon',
    'mus_radio_diamond_billieholiday_crazyhecallsme',
    'mus_radio_diamond_billieholiday_easyliving',
    'mus_radio_diamond_billywardandthedominoes_sixtyminuteman',
    'mus_radio_diamond_bingcrosby_accentuatethepositive',
    'mus_radio_diamond_bingcrosby_pistolpackinmama',
    'mus_radio_diamond_bobcrosby_dearheartsandgentlepeople',
    'mus_radio_diamond_bobcrosby_happytimes',
    'mus_radio_diamond_bobcrosby_waybackhome',
    'mus_radio_diamond_coleporter_anythinggoes',
    'mus_radio_diamond_connieallen_rocket69',
    'mus_radio_diamond_dannykaye_civilization',
    'mus_radio_diamond_dion_thewanderer',
    'mus_radio_diamond_dion_thewandererxxx',
    'mus_radio_diamond_ellafitzgerald_intoeachlife',
    'mus_radio_diamond_ellafitzgerald_undecided',
    'mus_radio_diamond_eltonbritt_uraniumfever',
    'mus_radio_diamond_frankiecarle_onemoretomorrow',
    'mus_radio_diamond_johnnymercer_personality',
    'mus_radio_diamond_louisjordan_keepaknockin',
    'mus_radio_diamond_natkingcole_orangecoloredsky',
    'mus_radio_diamond_raysmith_rightbehindyoubaby',
    'mus_radio_diamond_roybrown_butcherpetepart1',
    'mus_radio_diamond_roybrown_butcherpetepart2',
    'mus_radio_diamond_roybrown_goodrockintonight',
    'mus_radio_diamond_roybrown_mightymightyman',
    'mus_radio_diamond_sheldonallman_crawloutthroughthefallout',
    'mus_radio_diamond_skeeterdavis_theendoftheworld',
    'mus_radio_diamond_texbenekeawonderfulguy',
    'mus_radio_diamond_thefivestars_atombombbaby',
    'mus_radio_diamond_theinkspots_idontwanttoset',
    'mus_radio_diamond_theinkspots_itsalloverbutthecrying',
    'mus_radio_diamond_theinkspots_maybe',
    'mus_radio_diamond_thethreesuns_worryworryworry',
    'mus_radio_diamond_warrensmith_uraniumrock',
    'mus_radio_diamond_wynonieharris_grandmaplaysthenumbers'
]